edition = "2024"
style_edition = "2024"

control_brace_style = "ClosingNextLine"
error_on_line_overflow = true
error_on_unformatted = true
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
unstable_features = true
wrap_comments = true
