[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web.workspace = true
actix-http.workspace = true
async-trait.workspace = true
serde.workspace = true

auth.workspace = true
